#!/bin/bash

let upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
let secs=$((${upSeconds}%60))
let mins=$((${upSeconds}/60%60))
let hours=$((${upSeconds}/3600%24))
let days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

PROCCOUNT=`ps -l | wc -l`
PROCCOUNT=`expr $PROCCOUNT - 4`

# get the load averages
read one five fifteen rest < /proc/loadavg

echo -e "
+++++++++++++++++: System Data :+++++++++++++++++++
+ Date = `date +"%A, %e %B %Y, %r"`
+ Hostname = `hostname`
+ Kernel = `uname -srmo`
+ Uptime = ${UPTIME}
+ CPU = `grep -m 1 "model name" /proc/cpuinfo | cut -d: -f2  | sed -e 's/^ *//'`
+ Memory = `cat /proc/meminfo | grep MemTotal | awk {'print $2'}` kB
+++++++++++++++++: Network :+++++++++++++++++++++++
`/sbin/ifconfig |grep -B1 -E "inet addr|inet adr" |awk '{ if ( $1 == "inet" ) { print $2 } else if ( $2 == "Link" ) { printf "%s:" ,$1 } }' |awk -F: '{ print"+ " $1 " = " $3 }'`
++++++++++++++++++: System Load :++++++++++++++++++
+ Memory = `cat /proc/meminfo | grep MemFree | awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total)
+ Load Averages = ${one}, ${five}, ${fifteen} (1, 5, 15 min)
+ Running Processes = `ps ax | wc -l | tr -d " "`
++++++++++++++++++: User Data :++++++++++++++++++++
+ Username = `whoami`
+ Sessions = `who | grep $USER | wc -l`
+ Processes = $PROCCOUNT 
+++++++++++++++++++++++++++++++++++++++++++++++++++
"

